import React from 'react';
import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

//! import home page sections here
import Intro from '../HomePageSections/Intro'

const HomePage = () => {
  return (
    <React.Fragment>
        <Head>
          <title>Alex Beciana</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
            <Intro/>
    </React.Fragment>
  )
}

export default HomePage