import React, {useState, useEffect} from 'react';
import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

//! import home page sections here
import Intro from '../HomePageSections/Intro'
import About from '../HomePageSections/About'

const HomePage = () => {

  const [aboutAnimate, setAboutAnimate] = useState(false)

      const handleAboutScroll = () => {
        const offset = window.scrollY;
        if (offset > 450) {
            setAboutAnimate(true)
        } else {
            setAboutAnimate(false)
        }
    };

    useEffect(() => {
        window.addEventListener('scroll', handleAboutScroll);
    });

  return (
    <React.Fragment>
        <Head>
          <title>Alex Beciana</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Intro />
        <About aboutAnimate={aboutAnimate} />
    </React.Fragment>
  )
}

export default HomePage