import Document, { Html, Head, Main, NextScript } from 'next/document'

const MyDocument = () => {

    return (
        <Html>
            <Head>
                <title>Alex Beciana</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon preload" href="/waving.png" />
                <link rel="stylesheet preload" href="https://use.typekit.net/bsh6twa.css" crossOrigin="anonymous" />
                <link rel="preconnect preload" href="https://fonts.googleapis.com" crossOrigin="anonymous" />
                <link rel="preconnect preload" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
                <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono&display=swap" rel="stylesheet preload" crossOrigin="anonymous" />
                {/* <script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/21004082.js"></script> */}
            </Head>
            <body>
                <Main />
                <NextScript />
            </body>
        </Html>
    )
}

export default MyDocument